const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
let seconds=40*60,timerHandle=null;
const quiz=$('#quiz'),start=$('#startScreen');
function norm(s=''){return s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
function setFeedback(id,msg,type='good'){const e=$(id);e.textContent=msg;e.className='feedback '+type}
function begin(){start.classList.add('hidden');quiz.classList.remove('hidden');timerHandle=setInterval(()=>{if(seconds<=0){clearInterval(timerHandle);$('#timer').textContent='Zeit abgelaufen';return}seconds--;const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');$('#timer').textContent=`${m}:${s}`},1000);updateProgress();window.scrollTo({top:0,behavior:'smooth'})}
$('#startBtn').addEventListener('click',begin);

function checkMC(){const vals=$$('input[name="mc1"]:checked').map(x=>x.value).sort().join(',');const ok=vals==='c,h';setFeedback('#fb-mc1',ok?'Richtig: Kohlenstoff und Wasserstoff.':'Noch nicht. Prüfe, welche Stoffe als brennbare Hauptbestandteile genannt werden.',ok?'good':'bad')}
function checkMatching(){const sels=$$('.match-grid select');const n=sels.filter(s=>s.value===s.dataset.answer).length;setFeedback('#fb-matching',`${n} von ${sels.length} Zuordnungen richtig.`,n===sels.length?'good':'warn')}
function checkFire(){const vals=[$('#fire1').value,$('#fire2').value,$('#fire3').value].map(norm);const keys=['brennstoff','sauerstoff','zund'];const ok=keys.every(k=>vals.some(v=>v.includes(k)));setFeedback('#fb-fire',ok?'Vollständig: Brennstoff, Sauerstoff und Wärme/Zündenergie.':'Es fehlen noch Bestandteile des Feuerdreiecks.',ok?'good':'bad')}
function checkSulfur(){const sels=$$('#sulfurOrder select');const n=sels.filter(s=>s.value===s.dataset.answer).length;setFeedback('#fb-sulfur',`${n} von 5 Prozessschritten richtig.`,n===5?'good':'warn')}
function checkOil(){const v=parseFloat($('#oilResult').value.replace(',','.'));const ok=Math.abs(v-252)<0.2;setFeedback('#fb-oilcalc',ok?'Richtig: 252 kWh.':'Prüfe: Q = m · Hₛ.',ok?'good':'bad')}
function checkGas(){const v=parseFloat($('#gasResult').value.replace(',','.'));const ok=Math.abs(v-12.5)<0.15;setFeedback('#fb-gascalc',ok?'Richtig: 12,5 m³.':'Prüfe: V = Q / HₛB.',ok?'good':'bad')}
function checkTextfields(){let correct=0,total=3;const fields=$$('#station3 input[data-exact],#station3 input[data-contains]');fields.forEach(f=>{const v=norm(f.value);let ok=false;if(f.dataset.exact)ok=v===norm(f.dataset.exact);if(f.dataset.contains)ok=v.includes(norm(f.dataset.contains));f.classList.toggle('valid',ok);f.classList.toggle('invalid',!ok);if(ok)correct++});setFeedback('#fb-textfields',`${correct} von ${total} Kurzantworten passend.`,correct===total?'good':'warn')}
$$('[data-check]').forEach(b=>b.addEventListener('click',()=>({mc1:checkMC,matching:checkMatching,fire:checkFire,sulfur:checkSulfur,oilcalc:checkOil,gascalc:checkGas,textfields:checkTextfields}[b.dataset.check]||(()=>{}))()));

function addChatRows(n=8){const box=$('#chatRows');for(let i=0;i<n;i++){const row=document.createElement('label');row.className='chat-row';row.innerHTML=`<span>${(box.children.length%2===0)?'Lea:':'Tom:'}</span><input data-chat="true" placeholder="Fachlich formulierte Nachricht …">`;box.appendChild(row)}}addChatRows();$('#addChat').addEventListener('click',()=>addChatRows(2));

function wordCount(v){return v.trim()?v.trim().split(/\s+/).length:0}
function validateQualitative(){let required=$$('[data-required="true"]'),done=0;required.forEach(el=>{const min=+(el.dataset.minwords||1);const val=el.value||'';const kw=(el.dataset.keywords||'').split(',').filter(Boolean);const ok=wordCount(val)>=min && kw.every(k=>norm(val).includes(norm(k)));el.classList.toggle('invalid',!ok);el.classList.toggle('valid',ok);if(ok)done++});const checks=$$('[data-required-check]');checks.forEach(c=>{if(c.checked)done++; else c.closest('label').classList.add('invalid')});return {done,total:required.length+checks.length}}
function updateProgress(){const inputs=$$('input,textarea,select',quiz).filter(e=>!e.disabled&&e.type!=='button');const filled=inputs.filter(e=>e.type==='checkbox'?e.checked:(e.value||'').trim()!=='').length;const p=inputs.length?Math.round(filled/inputs.length*100):0;$('#progressBar').style.width=p+'%';$('#progressLabel').textContent=p+' %'}quiz.addEventListener('input',updateProgress);quiz.addEventListener('change',updateProgress);

$('#saveBtn').addEventListener('click',()=>{const data={};$$('input,textarea,select',quiz).forEach((el,i)=>data[i]=el.type==='checkbox'?el.checked:el.value);localStorage.setItem('brennstoffe-progress',JSON.stringify(data));$('#saveBtn').textContent='Gespeichert ✓';setTimeout(()=>$('#saveBtn').textContent='Zwischenstand speichern',1200)});
function restore(){const raw=localStorage.getItem('brennstoffe-progress');if(!raw)return;try{const data=JSON.parse(raw);$$('input,textarea,select',quiz).forEach((el,i)=>{if(!(i in data))return;if(el.type==='checkbox')el.checked=!!data[i];else el.value=data[i]});updateProgress()}catch{}}restore();

$('#printBtn').addEventListener('click',()=>window.print());
const dialog=$('#overviewDialog');$('#overviewBtn').addEventListener('click',()=>dialog.showModal());$('#closeOverview').addEventListener('click',()=>dialog.close());
const links=$('#stationLinks');$$('.station').forEach((s,i)=>{const a=document.createElement('a');a.href=`#${s.id}`;a.innerHTML=`Station ${i+1}: ${$('h2',s).textContent}<span>öffnen</span>`;a.addEventListener('click',()=>dialog.close());links.appendChild(a)});

$('#finishBtn').addEventListener('click',()=>{checkMC();checkMatching();checkFire();checkSulfur();checkOil();checkGas();checkTextfields();const q=validateQualitative();const chatFilled=$$('[data-chat="true"]').filter(i=>wordCount(i.value)>=3).length;setFeedback('#fb-chat',chatFilled>=8?`Fach-Chat vollständig: ${chatFilled} Nachrichten.`:`Erst ${chatFilled} von mindestens 8 ausreichend gefüllten Nachrichten.`,chatFilled>=8?'good':'warn');const unanswered=$$('input,textarea,select',quiz).filter(e=>e.type!=='checkbox'&&!e.closest('.no-print')&&(e.value||'').trim()==='').length;const box=$('#resultBox');box.classList.remove('hidden');box.innerHTML=`<div class="result-grid"><div><strong>${q.done}/${q.total}</strong><span>qualitative Pflichtfelder mit Mindestumfang</span></div><div><strong>${chatFilled}/8+</strong><span>Chat-Nachrichten</span></div><div><strong>${unanswered}</strong><span>noch leere Eingabefelder</span></div></div><p><strong>Abgabecheck:</strong> Automatische Rückmeldungen prüfen nur eindeutig kontrollierbare Teile. Offene Begründungen und Rechenwege müssen fachlich beurteilt werden.</p>`;box.scrollIntoView({behavior:'smooth',block:'center'})});
